/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Optional Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.Expression_Optional_Group#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Optional_Group()
 * @model
 * @generated
 */
public interface Expression_Optional_Group extends Expression
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Optional_Group_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link org.uasm.ebnf.eBNFLang.Expression_Optional_Group#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // Expression_Optional_Group
