/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Alternative</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.Expression_Alternative#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Alternative()
 * @model
 * @generated
 */
public interface Expression_Alternative extends Expression
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.uasm.ebnf.eBNFLang.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Alternative_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getElements();

} // Expression_Alternative
