/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Repetition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.Expression_Repetition#getRepetitions <em>Repetitions</em>}</li>
 *   <li>{@link org.uasm.ebnf.eBNFLang.Expression_Repetition#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Repetition()
 * @model
 * @generated
 */
public interface Expression_Repetition extends Expression
{
  /**
   * Returns the value of the '<em><b>Repetitions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Repetitions</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repetitions</em>' attribute.
   * @see #setRepetitions(int)
   * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Repetition_Repetitions()
   * @model
   * @generated
   */
  int getRepetitions();

  /**
   * Sets the value of the '{@link org.uasm.ebnf.eBNFLang.Expression_Repetition#getRepetitions <em>Repetitions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repetitions</em>' attribute.
   * @see #getRepetitions()
   * @generated
   */
  void setRepetitions(int value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Repetition_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link org.uasm.ebnf.eBNFLang.Expression_Repetition#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // Expression_Repetition
