/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Rule Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.Expression_Rule_Reference#getRule <em>Rule</em>}</li>
 * </ul>
 *
 * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Rule_Reference()
 * @model
 * @generated
 */
public interface Expression_Rule_Reference extends Expression
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' reference.
   * @see #setRule(ProductionRule)
   * @see org.uasm.ebnf.eBNFLang.EBNFLangPackage#getExpression_Rule_Reference_Rule()
   * @model
   * @generated
   */
  ProductionRule getRule();

  /**
   * Sets the value of the '{@link org.uasm.ebnf.eBNFLang.Expression_Rule_Reference#getRule <em>Rule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' reference.
   * @see #getRule()
   * @generated
   */
  void setRule(ProductionRule value);

} // Expression_Rule_Reference
