/*
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTermDslScopeProvider extends DelegatingScopeProvider {
}
