/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.BasicDomain#getTypeBasicDom <em>Type Basic Dom</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getBasicDomain()
 * @model
 * @generated
 */
public interface BasicDomain extends Domain
{
  /**
   * Returns the value of the '<em><b>Type Basic Dom</b></em>' attribute.
   * The literals are from the enumeration {@link org.uasm.term.lang.termDsl.BasicDomainEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Basic Dom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Basic Dom</em>' attribute.
   * @see org.uasm.term.lang.termDsl.BasicDomainEnum
   * @see #setTypeBasicDom(BasicDomainEnum)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getBasicDomain_TypeBasicDom()
   * @model
   * @generated
   */
  BasicDomainEnum getTypeBasicDom();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.BasicDomain#getTypeBasicDom <em>Type Basic Dom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Basic Dom</em>' attribute.
   * @see org.uasm.term.lang.termDsl.BasicDomainEnum
   * @see #getTypeBasicDom()
   * @generated
   */
  void setTypeBasicDom(BasicDomainEnum value);

} // BasicDomain
