/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getDomain()
 * @model
 * @generated
 */
public interface Domain extends EObject
{
} // Domain
