/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumerable Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.EnumerableTerm#getDom <em>Dom</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getEnumerableTerm()
 * @model
 * @generated
 */
public interface EnumerableTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Dom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dom</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dom</em>' containment reference.
   * @see #setDom(Domain)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getEnumerableTerm_Dom()
   * @model containment="true"
   * @generated
   */
  Domain getDom();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.EnumerableTerm#getDom <em>Dom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dom</em>' containment reference.
   * @see #getDom()
   * @generated
   */
  void setDom(Domain value);

} // EnumerableTerm
