/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For All Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.ForAllTerm#getVarTerm <em>Var Term</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.ForAllTerm#getInTerm <em>In Term</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.ForAllTerm#getWithTerm <em>With Term</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getForAllTerm()
 * @model
 * @generated
 */
public interface ForAllTerm extends BasicTerm
{
  /**
   * Returns the value of the '<em><b>Var Term</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Term</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Term</em>' attribute list.
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getForAllTerm_VarTerm()
   * @model unique="false"
   * @generated
   */
  EList<String> getVarTerm();

  /**
   * Returns the value of the '<em><b>In Term</b></em>' containment reference list.
   * The list contents are of type {@link org.uasm.term.lang.termDsl.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Term</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Term</em>' containment reference list.
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getForAllTerm_InTerm()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getInTerm();

  /**
   * Returns the value of the '<em><b>With Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>With Term</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Term</em>' containment reference.
   * @see #setWithTerm(Expression)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getForAllTerm_WithTerm()
   * @model containment="true"
   * @generated
   */
  Expression getWithTerm();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.ForAllTerm#getWithTerm <em>With Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With Term</em>' containment reference.
   * @see #getWithTerm()
   * @generated
   */
  void setWithTerm(Expression value);

} // ForAllTerm
