/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.FunctionTerm#getFunction <em>Function</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.FunctionTerm#getArgs <em>Args</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.FunctionTerm#getArgsTuple <em>Args Tuple</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getFunctionTerm()
 * @model
 * @generated
 */
public interface FunctionTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getFunctionTerm_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.FunctionTerm#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(Expression)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getFunctionTerm_Args()
   * @model containment="true"
   * @generated
   */
  Expression getArgs();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.FunctionTerm#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(Expression value);

  /**
   * Returns the value of the '<em><b>Args Tuple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args Tuple</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args Tuple</em>' containment reference.
   * @see #setArgsTuple(TupleTerm)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getFunctionTerm_ArgsTuple()
   * @model containment="true"
   * @generated
   */
  TupleTerm getArgsTuple();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.FunctionTerm#getArgsTuple <em>Args Tuple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args Tuple</em>' containment reference.
   * @see #getArgsTuple()
   * @generated
   */
  void setArgsTuple(TupleTerm value);

} // FunctionTerm
