/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interval Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.IntervalLiteral#getStart <em>Start</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.IntervalLiteral#getEnd <em>End</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.IntervalLiteral#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getIntervalLiteral()
 * @model
 * @generated
 */
public interface IntervalLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(Literal)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getIntervalLiteral_Start()
   * @model containment="true"
   * @generated
   */
  Literal getStart();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.IntervalLiteral#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(Literal value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(Literal)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getIntervalLiteral_End()
   * @model containment="true"
   * @generated
   */
  Literal getEnd();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.IntervalLiteral#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(Literal value);

  /**
   * Returns the value of the '<em><b>Step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Step</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' containment reference.
   * @see #setStep(Literal)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getIntervalLiteral_Step()
   * @model containment="true"
   * @generated
   */
  Literal getStep();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.IntervalLiteral#getStep <em>Step</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' containment reference.
   * @see #getStep()
   * @generated
   */
  void setStep(Literal value);

} // IntervalLiteral
