/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends BasicTerm
{
} // Literal
