/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getMapTerm()
 * @model
 * @generated
 */
public interface MapTerm extends StructureTerm
{
} // MapTerm
