/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.NumberLiteral#getValue <em>Value</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.NumberLiteral#getValueDec <em>Value Dec</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getNumberLiteral()
 * @model
 * @generated
 */
public interface NumberLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getNumberLiteral_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.NumberLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Value Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Dec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Dec</em>' attribute.
   * @see #setValueDec(BigDecimal)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getNumberLiteral_ValueDec()
   * @model
   * @generated
   */
  BigDecimal getValueDec();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.NumberLiteral#getValueDec <em>Value Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Dec</em>' attribute.
   * @see #getValueDec()
   * @generated
   */
  void setValueDec(BigDecimal value);

} // NumberLiteral
