/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule As Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.RuleAsTerm#getRule <em>Rule</em>}</li>
 * </ul>
 *
 * @see org.uasm.term.lang.termDsl.TermDslPackage#getRuleAsTerm()
 * @model
 * @generated
 */
public interface RuleAsTerm extends BasicTerm
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' attribute.
   * @see #setRule(String)
   * @see org.uasm.term.lang.termDsl.TermDslPackage#getRuleAsTerm_Rule()
   * @model
   * @generated
   */
  String getRule();

  /**
   * Sets the value of the '{@link org.uasm.term.lang.termDsl.RuleAsTerm#getRule <em>Rule</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' attribute.
   * @see #getRule()
   * @generated
   */
  void setRule(String value);

} // RuleAsTerm
