/*
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uasm.term.lang.parser.antlr.internal.InternalTermDslParser;
import org.uasm.term.lang.services.TermDslGrammarAccess;

public class TermDslParser extends AbstractAntlrParser {

	@Inject
	private TermDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTermDslParser createParser(XtextTokenStream stream) {
		return new InternalTermDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Term";
	}

	public TermDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TermDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
