/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uasm.ebnf.eBNFLang.EBNFLangPackage;
import org.uasm.ebnf.eBNFLang.Expression;
import org.uasm.ebnf.eBNFLang.Expression_Repetition_Group;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression Repetition Group</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.impl.Expression_Repetition_GroupImpl#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.uasm.ebnf.eBNFLang.impl.Expression_Repetition_GroupImpl#isAtLeastOne <em>At Least One</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Expression_Repetition_GroupImpl extends ExpressionImpl implements Expression_Repetition_Group
{
  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expression expr;

  /**
   * The default value of the '{@link #isAtLeastOne() <em>At Least One</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAtLeastOne()
   * @generated
   * @ordered
   */
  protected static final boolean AT_LEAST_ONE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isAtLeastOne() <em>At Least One</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAtLeastOne()
   * @generated
   * @ordered
   */
  protected boolean atLeastOne = AT_LEAST_ONE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Expression_Repetition_GroupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EBNFLangPackage.Literals.EXPRESSION_REPETITION_GROUP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expression newExpr, NotificationChain msgs)
  {
    Expression oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpr(Expression newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isAtLeastOne()
  {
    return atLeastOne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtLeastOne(boolean newAtLeastOne)
  {
    boolean oldAtLeastOne = atLeastOne;
    atLeastOne = newAtLeastOne;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION_GROUP__AT_LEAST_ONE, oldAtLeastOne, atLeastOne));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR:
        return basicSetExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR:
        return getExpr();
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__AT_LEAST_ONE:
        return isAtLeastOne();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR:
        setExpr((Expression)newValue);
        return;
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__AT_LEAST_ONE:
        setAtLeastOne((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR:
        setExpr((Expression)null);
        return;
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__AT_LEAST_ONE:
        setAtLeastOne(AT_LEAST_ONE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__EXPR:
        return expr != null;
      case EBNFLangPackage.EXPRESSION_REPETITION_GROUP__AT_LEAST_ONE:
        return atLeastOne != AT_LEAST_ONE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (atLeastOne: ");
    result.append(atLeastOne);
    result.append(')');
    return result.toString();
  }

} //Expression_Repetition_GroupImpl
