/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uasm.ebnf.eBNFLang.EBNFLangPackage;
import org.uasm.ebnf.eBNFLang.Expression_Rule_Reference;
import org.uasm.ebnf.eBNFLang.ProductionRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression Rule Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.impl.Expression_Rule_ReferenceImpl#getRule <em>Rule</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Expression_Rule_ReferenceImpl extends ExpressionImpl implements Expression_Rule_Reference
{
  /**
   * The cached value of the '{@link #getRule() <em>Rule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRule()
   * @generated
   * @ordered
   */
  protected ProductionRule rule;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Expression_Rule_ReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EBNFLangPackage.Literals.EXPRESSION_RULE_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductionRule getRule()
  {
    if (rule != null && rule.eIsProxy())
    {
      InternalEObject oldRule = (InternalEObject)rule;
      rule = (ProductionRule)eResolveProxy(oldRule);
      if (rule != oldRule)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE, oldRule, rule));
      }
    }
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProductionRule basicGetRule()
  {
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRule(ProductionRule newRule)
  {
    ProductionRule oldRule = rule;
    rule = newRule;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE, oldRule, rule));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE:
        if (resolve) return getRule();
        return basicGetRule();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE:
        setRule((ProductionRule)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE:
        setRule((ProductionRule)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_RULE_REFERENCE__RULE:
        return rule != null;
    }
    return super.eIsSet(featureID);
  }

} //Expression_Rule_ReferenceImpl
