/**
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.eBNFLang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uasm.ebnf.eBNFLang.EBNFLangPackage;
import org.uasm.ebnf.eBNFLang.Expression;
import org.uasm.ebnf.eBNFLang.Expression_Repetition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression Repetition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.ebnf.eBNFLang.impl.Expression_RepetitionImpl#getRepetitions <em>Repetitions</em>}</li>
 *   <li>{@link org.uasm.ebnf.eBNFLang.impl.Expression_RepetitionImpl#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Expression_RepetitionImpl extends ExpressionImpl implements Expression_Repetition
{
  /**
   * The default value of the '{@link #getRepetitions() <em>Repetitions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRepetitions()
   * @generated
   * @ordered
   */
  protected static final int REPETITIONS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRepetitions() <em>Repetitions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRepetitions()
   * @generated
   * @ordered
   */
  protected int repetitions = REPETITIONS_EDEFAULT;

  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expression expr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Expression_RepetitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EBNFLangPackage.Literals.EXPRESSION_REPETITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getRepetitions()
  {
    return repetitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRepetitions(int newRepetitions)
  {
    int oldRepetitions = repetitions;
    repetitions = newRepetitions;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION__REPETITIONS, oldRepetitions, repetitions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expression newExpr, NotificationChain msgs)
  {
    Expression oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpr(Expression newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EBNFLangPackage.EXPRESSION_REPETITION__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EBNFLangPackage.EXPRESSION_REPETITION__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EBNFLangPackage.EXPRESSION_REPETITION__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION__EXPR:
        return basicSetExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION__REPETITIONS:
        return getRepetitions();
      case EBNFLangPackage.EXPRESSION_REPETITION__EXPR:
        return getExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION__REPETITIONS:
        setRepetitions((Integer)newValue);
        return;
      case EBNFLangPackage.EXPRESSION_REPETITION__EXPR:
        setExpr((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION__REPETITIONS:
        setRepetitions(REPETITIONS_EDEFAULT);
        return;
      case EBNFLangPackage.EXPRESSION_REPETITION__EXPR:
        setExpr((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EBNFLangPackage.EXPRESSION_REPETITION__REPETITIONS:
        return repetitions != REPETITIONS_EDEFAULT;
      case EBNFLangPackage.EXPRESSION_REPETITION__EXPR:
        return expr != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (repetitions: ");
    result.append(repetitions);
    result.append(')');
    return result.toString();
  }

} //Expression_RepetitionImpl
