/*
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.uasm.term.lang.termDsl.Expression

@RunWith(XtextRunner)
@InjectWith(TermDslInjectorProvider)
class TermDslParsingTest{

	@Inject
	ParseHelper<Expression> parseHelper

	@Test 
	def void loadModel() {
		var result = parseHelper.parse("a and b")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		//
		result = parseHelper.parse("a * b > 0")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		//
		result = parseHelper.parse("true and b > 0 or 1 + 4 = 5")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		//
		result = parseHelper.parse("result + 2")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		//
		result = parseHelper.parse("a = |B|")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)

		result = parseHelper.parse("get_2(a,b)")
		
		result = parseHelper.parse("at((a,b),2) > at((a,b),2)")
		result = parseHelper.parse("get_2(a,b)")
		result = parseHelper.parse("getnth((a,b),2) > at((a,b),2)")
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		// set((a,b),x,c) = if (x == 1) then (c,  
		result = parseHelper.parse("(a,c) = set_2((a,b),c)") // TRUE
		result = parseHelper.parse("(a,c) = set((a,b),2,c)") // TRUE
		result = parseHelper.parse("(a,c) = setnth((a,b),2,c)") // TRUE
		print(result.toString + " type " + result.class.canonicalName)
		Assert.assertNotNull(result)
		
	}

}
