/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uasm.term.lang.termDsl.BasicDomain;
import org.uasm.term.lang.termDsl.BasicDomainEnum;
import org.uasm.term.lang.termDsl.TermDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Domain</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.impl.BasicDomainImpl#getTypeBasicDom <em>Type Basic Dom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BasicDomainImpl extends DomainImpl implements BasicDomain
{
  /**
   * The default value of the '{@link #getTypeBasicDom() <em>Type Basic Dom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeBasicDom()
   * @generated
   * @ordered
   */
  protected static final BasicDomainEnum TYPE_BASIC_DOM_EDEFAULT = BasicDomainEnum.STRING;

  /**
   * The cached value of the '{@link #getTypeBasicDom() <em>Type Basic Dom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeBasicDom()
   * @generated
   * @ordered
   */
  protected BasicDomainEnum typeBasicDom = TYPE_BASIC_DOM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TermDslPackage.Literals.BASIC_DOMAIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BasicDomainEnum getTypeBasicDom()
  {
    return typeBasicDom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeBasicDom(BasicDomainEnum newTypeBasicDom)
  {
    BasicDomainEnum oldTypeBasicDom = typeBasicDom;
    typeBasicDom = newTypeBasicDom == null ? TYPE_BASIC_DOM_EDEFAULT : newTypeBasicDom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TermDslPackage.BASIC_DOMAIN__TYPE_BASIC_DOM, oldTypeBasicDom, typeBasicDom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TermDslPackage.BASIC_DOMAIN__TYPE_BASIC_DOM:
        return getTypeBasicDom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TermDslPackage.BASIC_DOMAIN__TYPE_BASIC_DOM:
        setTypeBasicDom((BasicDomainEnum)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TermDslPackage.BASIC_DOMAIN__TYPE_BASIC_DOM:
        setTypeBasicDom(TYPE_BASIC_DOM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TermDslPackage.BASIC_DOMAIN__TYPE_BASIC_DOM:
        return typeBasicDom != TYPE_BASIC_DOM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (typeBasicDom: ");
    result.append(typeBasicDom);
    result.append(')');
    return result.toString();
  }

} //BasicDomainImpl
