/**
 * generated by Xtext 2.10.0
 */
package org.uasm.term.lang.termDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uasm.term.lang.termDsl.ConditionalTerm;
import org.uasm.term.lang.termDsl.Expression;
import org.uasm.term.lang.termDsl.TermDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conditional Term</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uasm.term.lang.termDsl.impl.ConditionalTermImpl#getCond <em>Cond</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.impl.ConditionalTermImpl#getThenTerm <em>Then Term</em>}</li>
 *   <li>{@link org.uasm.term.lang.termDsl.impl.ConditionalTermImpl#getElseTerm <em>Else Term</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConditionalTermImpl extends BasicTermImpl implements ConditionalTerm
{
  /**
   * The cached value of the '{@link #getCond() <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCond()
   * @generated
   * @ordered
   */
  protected Expression cond;

  /**
   * The cached value of the '{@link #getThenTerm() <em>Then Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenTerm()
   * @generated
   * @ordered
   */
  protected Expression thenTerm;

  /**
   * The cached value of the '{@link #getElseTerm() <em>Else Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElseTerm()
   * @generated
   * @ordered
   */
  protected Expression elseTerm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionalTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TermDslPackage.Literals.CONDITIONAL_TERM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getCond()
  {
    return cond;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCond(Expression newCond, NotificationChain msgs)
  {
    Expression oldCond = cond;
    cond = newCond;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__COND, oldCond, newCond);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCond(Expression newCond)
  {
    if (newCond != cond)
    {
      NotificationChain msgs = null;
      if (cond != null)
        msgs = ((InternalEObject)cond).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__COND, null, msgs);
      if (newCond != null)
        msgs = ((InternalEObject)newCond).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__COND, null, msgs);
      msgs = basicSetCond(newCond, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__COND, newCond, newCond));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getThenTerm()
  {
    return thenTerm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThenTerm(Expression newThenTerm, NotificationChain msgs)
  {
    Expression oldThenTerm = thenTerm;
    thenTerm = newThenTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__THEN_TERM, oldThenTerm, newThenTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setThenTerm(Expression newThenTerm)
  {
    if (newThenTerm != thenTerm)
    {
      NotificationChain msgs = null;
      if (thenTerm != null)
        msgs = ((InternalEObject)thenTerm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__THEN_TERM, null, msgs);
      if (newThenTerm != null)
        msgs = ((InternalEObject)newThenTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__THEN_TERM, null, msgs);
      msgs = basicSetThenTerm(newThenTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__THEN_TERM, newThenTerm, newThenTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getElseTerm()
  {
    return elseTerm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElseTerm(Expression newElseTerm, NotificationChain msgs)
  {
    Expression oldElseTerm = elseTerm;
    elseTerm = newElseTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__ELSE_TERM, oldElseTerm, newElseTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElseTerm(Expression newElseTerm)
  {
    if (newElseTerm != elseTerm)
    {
      NotificationChain msgs = null;
      if (elseTerm != null)
        msgs = ((InternalEObject)elseTerm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__ELSE_TERM, null, msgs);
      if (newElseTerm != null)
        msgs = ((InternalEObject)newElseTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TermDslPackage.CONDITIONAL_TERM__ELSE_TERM, null, msgs);
      msgs = basicSetElseTerm(newElseTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TermDslPackage.CONDITIONAL_TERM__ELSE_TERM, newElseTerm, newElseTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TermDslPackage.CONDITIONAL_TERM__COND:
        return basicSetCond(null, msgs);
      case TermDslPackage.CONDITIONAL_TERM__THEN_TERM:
        return basicSetThenTerm(null, msgs);
      case TermDslPackage.CONDITIONAL_TERM__ELSE_TERM:
        return basicSetElseTerm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TermDslPackage.CONDITIONAL_TERM__COND:
        return getCond();
      case TermDslPackage.CONDITIONAL_TERM__THEN_TERM:
        return getThenTerm();
      case TermDslPackage.CONDITIONAL_TERM__ELSE_TERM:
        return getElseTerm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TermDslPackage.CONDITIONAL_TERM__COND:
        setCond((Expression)newValue);
        return;
      case TermDslPackage.CONDITIONAL_TERM__THEN_TERM:
        setThenTerm((Expression)newValue);
        return;
      case TermDslPackage.CONDITIONAL_TERM__ELSE_TERM:
        setElseTerm((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TermDslPackage.CONDITIONAL_TERM__COND:
        setCond((Expression)null);
        return;
      case TermDslPackage.CONDITIONAL_TERM__THEN_TERM:
        setThenTerm((Expression)null);
        return;
      case TermDslPackage.CONDITIONAL_TERM__ELSE_TERM:
        setElseTerm((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TermDslPackage.CONDITIONAL_TERM__COND:
        return cond != null;
      case TermDslPackage.CONDITIONAL_TERM__THEN_TERM:
        return thenTerm != null;
      case TermDslPackage.CONDITIONAL_TERM__ELSE_TERM:
        return elseTerm != null;
    }
    return super.eIsSet(featureID);
  }

} //ConditionalTermImpl
