/*
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EBNFLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/uasm/ebnf/parser/antlr/internal/InternalEBNFLang.tokens");
	}
}
