/*
 * generated by Xtext 2.10.0
 */
package org.uasm.ebnf.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uasm.ebnf.parser.antlr.internal.InternalEBNFLangParser;
import org.uasm.ebnf.services.EBNFLangGrammarAccess;

public class EBNFLangParser extends AbstractAntlrParser {

	@Inject
	private EBNFLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEBNFLangParser createParser(XtextTokenStream stream) {
		return new InternalEBNFLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EbnfGrammar";
	}

	public EBNFLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EBNFLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
